apiVersion: v1
kind: Service
metadata:
  name: sonar
spec:
  type: NodePort
  ports:
    - name: sonar
      port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonar
  type: LoadBalancer
