apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - name: sonar
          image: sonarqube:7.1
          env:
            - name: "SONARQUBE_JDBC_USERNAME"
              value: sonar
            - name: "SONARQUBE_JDBC_URL"
              value: "jdbc:postgresql://postgres/sonar"
            - name: "SONARQUBE_JDBC_PASSWORD"
              value: sonar
          ports:
            - containerPort: 9000
              protocol: TCP
