---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-configuration-as-code
data:
  configuration-as-code.yaml: |
    jenkins:
      clouds:
        - kubernetes:
            name: "kubernetes"
            namespace: "default"
            connectTimeout: 5
            readTimeout: 15
            concurrencyLimit: 10
            maxRequestsPerHostStr: 32
            containerCapStr: 600
            templates:
              - name: "jenkins-slave"
                label: "jenkins-slave"
                containers:
                    - name: "jenkins-slave"
                      image: "jenkinsci/jnlp-slave"
                      workingDir: "/home/jenkins"
                      ttyEnabled: true
