---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-configuration-as-code
data:
  configuration-as-code.yaml: |
    jenkins:
      clouds:
        - kubernetes:
            name: "kubernetes"
            namespace: "default"
            jenkinsUrl: "http://jenkins/"
            templates:
              - name: "jenkins-slave"
                label: "jenkins-slave"
                containers:
                    - name: "jenkins-slave"
                      image: "jenkinsci/jnlp-slave"
